language: android
dist: precise
sudo: required
jdk:
- oraclejdk8

env:
  global:
    # switch glibc to a memory conserving mode
    - MALLOC_ARENA_MAX=2

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

android:
  components:
    - tools 
    - platform-tools
    - build-tools-26.0.2
    - tools
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew build
